apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: frontend-web
  template:
    metadata:
      labels:
        app: frontend-web
    spec:
      containers:
        - name: web-engin
          image: httpd
          resources:
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /tmp/conf
              name: conf-file
      volumes:
        - name: conf-file
          configMap:
            name: httpd-conf
